apiVersion: v1
kind: Pod
metadata:
  name: setup
spec:
  restartPolicy: Never
  containers:
  - name: setup
    image: anthonyamanse/mysql-bookinfo
    imagePullPolicy: Always
    env:
    - name: MYSQL_DB_USER
      value: 'admin'
    - name: MYSQL_DB_PASSWORD
      value: 'YICIKXHVMSPLXINF'
    - name: MYSQL_DB_HOST
      value: 'sl-us-dal-9-portal.5.dblayer.com'
    - name: MYSQL_DB_PORT
      value: '23966'
