apiVersion: v1
kind: Service
metadata:
  name: post
  labels:
    app: post
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: post
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: post-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: post
        version: v1
    spec:
      containers:
      - name: post
        image: anthonyamanse/test-post-v1:testPost5
        imagePullPolicy: Always
        env:
        - name: MYSQL_DB_USER
          value: 'admin'
        - name: MYSQL_DB_PASSWORD
          value: 'YICIKXHVMSPLXINF'
        - name: MYSQL_DB_HOST
          value: 'sl-us-dal-9-portal.5.dblayer.com'
        - name: MYSQL_DB_PORT
          value: '23966'
        - name: SLACK_WEBHOOK_URL
          value: 'https://hooks.slack.com/services/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'
        ports:
        - containerPort: 9080
