apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: anthonyamanse/reviews-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DB_USER
          value: 'admin'
        - name: MYSQL_DB_PASSWORD
          value: 'YICIKXHVMSPLXINF'
        - name: MYSQL_DB_HOST
          value: 'sl-us-dal-9-portal.5.dblayer.com'
        - name: MYSQL_DB_PORT
          value: '23966'
        ports:
        - containerPort: 9080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews
        image: anthonyamanse/reviews-v2
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DB_USER
          value: 'admin'
        - name: MYSQL_DB_PASSWORD
          value: 'YICIKXHVMSPLXINF'
        - name: MYSQL_DB_HOST
          value: 'sl-us-dal-9-portal.5.dblayer.com'
        - name: MYSQL_DB_PORT
          value: '23966'
        ports:
        - containerPort: 9080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews
        image: anthonyamanse/reviews-v3
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DB_USER
          value: 'admin'
        - name: MYSQL_DB_PASSWORD
          value: 'YICIKXHVMSPLXINF'
        - name: MYSQL_DB_HOST
          value: 'sl-us-dal-9-portal.5.dblayer.com'
        - name: MYSQL_DB_PORT
          value: '23966'
        ports:
        - containerPort: 9080
